### ISSUE TITLE
Correct mock example

### ISSUE THREAD

**Issue by voidspace** [garybernhardt/python-mock-comparison#1]
Hey Gary,

github has the wrong ssh keys for me so this was easier than a pull request, sorry.

Patch here: https://gist.github.com/856510

As well as correcting a mock example it removes the broken links from index.rst. I also had to add the current directory to sys.path in conf.py in order to be able to execute the doctests on my system.

**Comment by garybernhardt** [comment]
Thanks! Committed and pushed to the hosted site.
